[project]
name = "product-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ryan McGuinness", email = "rmcguinness@google.com" }
]
requires-python = "==3.13.*"
dependencies = [
    "google-adk>=1.28.0",
    "google-genai>=1.70.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.2",
    "pydantic>=2.12.5",
    "reportlab>=4.4.10",
]

[project.scripts]
product-gen = "product_gen.process:main"

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"
